### ISSUE TITLE
大量に食わせると起こるエラー？

### ISSUE THREAD

**Issue by tamada** [tamada/pochi#11]
### 概要

* pochiに50個 (10230class) のjarファイルを食わせて，相互比較した (食わせたのはクラス)
* 以下エラー内容です．

```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 28263
at org.objectweb.asm.ClassReader.readClass(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at org.objectweb.asm.ClassReader.accept(Unknown Source)
at com.github.pochi.birthmarks.extractors.AbstractExtractor.accept(AbstractExtractor.java:45)
at com.github.pochi.birthmarks.extractors.AbstractExtractor.extractImpl(AbstractExtractor.java:39)
at com.github.pochi.birthmarks.extractors.AbstractExtractor.extractEach(AbstractExtractor.java:29)
at com.github.pochi.birthmarks.extractors.Extractor.lambda$extractForStream$1(Extractor.java:23)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at com.github.pochi.birthmarks.entities.Birthmarks.<init>(Birthmarks.java:15)
at com.github.pochi.birthmarks.extractors.Extractor.extract(Extractor.java:28)
at jdk.nashorn.internal.scripts.Script$Recompilation$6$155$\^eval\_.extract#time(<eval>:6)
at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)
at com.github.pochi.runner.scripts.helper.SystemInfoHelper.measure(SystemInfoHelper.java:11)
at jdk.nashorn.internal.scripts.Script$Recompilation$3$30AA$\^eval\_.extract(<eval>:5)
at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program(<eval>:21)
at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
at com.github.pochi.runner.scripts.ScriptRunner.runsScript(ScriptRunner.java:87)
at com.github.pochi.runner.ui.Arguments.perform(Arguments.java:59)
at com.github.pochi.runner.ui.Main.perform(Main.java:20)
at com.github.pochi.runner.ui.Main.<init>(Main.java:14)
at com.github.pochi.runner.ui.Main.main(Main.java:27)
```

* 30jar (7481class) を相互比較すると落ちない
* pochiに食わせたjsファイルは以下です．

```js
extract = function(type, from){
  extractor = engine.extractor(type);
  source = engine.source(from)
  obj = {}
  obj.time = sys.measure(function(){
    obj.birthmarks = extractor.extract(source);
  })
  return obj;
}

compare = function(pair, compare, birthmarks){
  pair = engine.pairMatcher("RoundRobinWithSamePair")
  comparator = engine.comparator("JaccardIndex")
  obj = {};
  obj.time = sys.measure(function(){
    obj.comparisons = comparator.compare(birthmarks, pair);
  });
  return obj;
}

extractResult = extract("2-gram", "class/");
compareResult = compare("RoundRobin", "JaccardIndex", extractResult.birthmarks);

compareResult.comparisons.forEach(function(comparison){
print(comparison);
});

fs.print("extraction: " + extractResult.time + " ns")
fs.print("comparison: " + compareResult.time + " ns")
```

**Comment by tamada** [comment]
@mitubaEX pochiのバグではなく，クラスファイルのフォーマットの違いのような気がしています．
とりあえず，どのクラスで起こったのか特定したいと思います．

extractorやcomparator にコールバック関数を追加しました（今後も残すかは未定）．
fix/arrayindexoutofboundsexception ブランチに追加したものがあります．
挙げてくれた JavaScript をもとに次のプログラムを作成しました．

このプログラムを実行して，例外が起こるクラスを特定してもらえませんか．

```js
extract = function(type, from){
  extractor = engine.extractor(type);
  source = engine.source(from);
  obj = {}
  obj.time = sys.measure(function(){
    obj.birthmarks = extractor.extract(source, function(entry){
      fs.print(entry.className())
    });
  });
  return obj;
}
compare = function(pairingAlgorithm, comparatorAlgorithm, birthmarks){
  pair = engine.pairMatcher(pairingAlgorithm)
  comparator = engine.comparator(comparatorAlgorithm)
  obj = {}
  obj.time = sys.measure(function(){
    obj.comparisons = comparator.compare(birthmarks, pair)
  })
  return obj
}

extractResult = extract("2-gram", argv[1])
compareResult = compare("RoundRobin", "JaccardIndex", extractResult.birthmarks)

compareResult.comparisons.forEach(function(comparison){
  print(comparison)
})

fs.print("extraction: " + extractResult.time + " ns")
fs.print("comparison: " + compareResult.time + " ns")
```

よろしくお願いします．

**Comment by mitubaEX** [comment]
@tamada ありがとうございます🙇‍♂️．

**`fix/arrayindexoutofboundsexception`** のブランチでの実行結果を以下に示します．

なお上記のプログラムを **`compare_test.js`** という名前で保存して，実行しています．

```console
$ java -jar target/pochi-runner-1.0-SNAPSHOT.jar compare_test.js class/
AbstractAggregatingDefaultQueryPersonAttributeDao
.
.
.
Statements
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 28263
.
.
.
$
```
エラーを見ると抽出段階でこけています．

単体ファイル **`Statements.class`** をpochiに食わせてみました．

```console
$ java -jar target/pochi-runner-1.0-SNAPSHOT.jar compare_test.js class/Statements.class
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 28263
        at org.objectweb.asm.ClassReader.readClass(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.github.pochi.kunai.source.ClassNameExtractVisitor.extractClassName(ClassNameExtractVisitor.java:30)
        at com.github.pochi.kunai.source.PathResolver.resolveClassName(PathResolver.java:15)
        at com.github.pochi.kunai.source.ClassFileDataSource.extractClassName(ClassFileDataSource.java:45)
        at com.github.pochi.kunai.source.ClassFileDataSource.parseClassName(ClassFileDataSource.java:39)
        at com.github.pochi.kunai.entries.PathEntry.className(PathEntry.java:25)
        at jdk.nashorn.internal.scripts.Script$Recompilation$7$212A$\^eval\_.extract#time#birthmarks(<eval>:7)
        at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source)
        at com.github.pochi.birthmarks.extractors.AbstractExtractor.extractImpl(AbstractExtractor.java:40)
        at com.github.pochi.birthmarks.extractors.AbstractExtractor.extractEach(AbstractExtractor.java:30)
        at com.github.pochi.birthmarks.extractors.Extractor.lambda$extractForStream$2(Extractor.java:27)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.github.pochi.birthmarks.entities.Birthmarks.<init>(Birthmarks.java:14)
        at com.github.pochi.birthmarks.extractors.Extractor.extract(Extractor.java:36)
        at jdk.nashorn.internal.scripts.Script$Recompilation$6$148$\^eval\_.extract#time(<eval>:6)
        at jdk.nashorn.javaadapters.java.lang.Runnable.run(Unknown Source)
        at com.github.pochi.runner.scripts.helper.SystemInfoHelper.measure(SystemInfoHelper.java:11)
        at jdk.nashorn.internal.scripts.Script$Recompilation$3$30AA$\^eval\_.extract(<eval>:5)
        at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program(<eval>:22)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at com.github.pochi.runner.scripts.ScriptRunner.runsScript(ScriptRunner.java:87)
        at com.github.pochi.runner.ui.Arguments.perform(Arguments.java:59)
        at com.github.pochi.runner.ui.Main.perform(Main.java:20)
        at com.github.pochi.runner.ui.Main.<init>(Main.java:14)
        at com.github.pochi.runner.ui.Main.main(Main.java:27)
```

**`Statements.class`** は[mm-mysql-2.0.7.jar](https://mvnrepository.com/artifact/mm-mysql/mm-mysql/2.0.7)の中のClassでした．

そして `class file`は，`jar xvf <jar file>`で取り出しました．

#### 質問

pochiは `csv` もしくは `class` を食わせることができますが，`jar` は食わせることができないようなのですが食わすことは可能でしょうか？

よろしくお願いします．🙇‍♂️

**Comment by tamada** [comment]
@mitubaEX ありがとう．こちらでも再現することを確認しました．
これからデバッグしてみます．

> pochiは csv もしくは class を食わせることができますが，jar は食わせることができないようなのですが食わすことは可能でしょうか？

問題なくできます．
```js
  source = engine.source(from);
```
に渡す from が jar でもクラスファイルでもディレクトリでも，war でもOKのはずです．

**Comment by tamada** [comment]
testsuites.Statements が壊れていますね．
javap でも Constant_pool を読むときにエラーが起きています．

```
エラー: testsuite/Statements.classの定数プールの読取り中にエラーが発生しました: unexpected tag at #1: 13
```

エラーが起こったときに，終了するのか，無視するのかのオプションでもつけようと思います．

**Comment by tamada** [comment]
エラーの時にコールバック関数を呼び出せるようにしました．
```src/sample/extract.js``` を参照してください．

```js
  obj.time = sys.measure(function(){
    obj.birthmarks = extractor.extract(source, function(entry, exception){
      fs.print(entry.className()) // デバッグ用
      fs.print(exception.getClass().getName()) // デバッグ用
    });
```

**Comment by tamada** [comment]
Resolved by #18
